# Assignment No1. Implement 50 methods of Numpy

### Create Numpy Array using np.array method

In [24]:
import numpy as np
var1 = np.array(range(5)) #1st Method
var1

array([0, 1, 2, 3, 4])

In [25]:
var2 = np.zeros(4)        #2nd Method
print(var2)
var2 = np.zeros((2,3,4)) # zeros(Dimentions , row , column)
var2

[0. 0. 0. 0.]


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
var3 = np.ones(5)          #3rd Method
print(var3)
var3 = np.ones(5 , dtype=np.int)
print(var3)
var3 = np.ones(5 , dtype=np.bool)
print(var3)
var3 = np.ones(5 , dtype=np.str)
var3

[1. 1. 1. 1. 1.]
[1 1 1 1 1]
[ True  True  True  True  True]


array(['1', '1', '1', '1', '1'], dtype='<U1')

In [27]:
var4 = np.arange(7)         #4rth Method
print(var4)
var4 = np.arange(0,11,2) #arange(StartingPoint , Endingpoint_Excluded , Increament)
var4

[0 1 2 3 4 5 6]


array([ 0,  2,  4,  6,  8, 10])

In [28]:
var5 = np.empty(5)           #5th Method
var5 #it will returns the random value from the memory

array([5.e-324, 5.e-324, 5.e-324, 5.e-324, 5.e-324])

In [29]:
var6 = np.linspace(0,11,5)   #6th Method
#linspace(StartingPoint , Ending_Point_Included , Total_number Or specific Interval Points)
var6

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

# ndarray 

In [30]:
var7 = np.arange(3*4*4).reshape(3,4,4) #7th Method
var7

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [31]:
var7.shape #8th Method

(3, 4, 4)

In [32]:
var7.ndim #9th Method

3

In [33]:
var7.dtype #10th Method

dtype('int64')

In [34]:
var7.dtype.name                #11th Method

'int64'

In [35]:
var7.itemsize                  #12th Method>>>>>>>>>Length of one array element in bytes.

8

In [36]:
var7.size                       #13 Method Size of array

48

In [37]:
type(var7)                     #14 Method

numpy.ndarray

# Sorting

In [38]:
var8 = np.array([9,8,6,3,5,2,7,4,1])
print(np.sort(var8))            #15th Method>> Sorting the whole array


[1 2 3 4 5 6 7 8 9]


In [39]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a,b)))    # 16th Method Concatenatoins

[1 2 3 4 5 6 7 8]


# How to convert a 1D array into a 2D array (how to add a new axis to an array)


In [46]:
var9 = np.array([1,2,3,4,5,6,7])
var9 = var9[np.newaxis,:]        #  17th Method
print(var9)
var9.shape

[[1 2 3 4 5 6 7]]


(1, 7)

In [47]:
var9 = np.array([1,2,3,4,5,6,7])
var9 = var9[:,np.newaxis]
print(var9)
var9.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


(7, 1)

In [55]:
a = np.array([1,2,3,4,5,6,7,8,9])
var10 = np.expand_dims(a , axis=1)#18 Method>>>>Second method Used for expending the dimention on Y-axis
print(var10.shape)
var10

(9, 1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [56]:
a = np.array([1,2,3,4,5,6,7,8,9])
var10 = np.expand_dims(a , axis=0)#18 Method>>>>Second method Used for expending the dimention on X-axis
print(var10.shape)
var10

(1, 9)


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [61]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
var11 = a[np.nonzero(a)]          #19th Method>>>>>>>It will return all non zero elements 
var11

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a = np.array([[0,1,2,3,4],[34,664,23,5,4],[13,68,8,4,2]])
var11 = np.nonzero(a<5)           #19th Method>>>>>>>It will return all non zero elements 
var11

(array([0, 0, 0, 0, 0, 1, 2, 2]), array([0, 1, 2, 3, 4, 4, 3, 4]))

# How to create an array from existing data

In [70]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
         [4, 4]])
var12 = np.vstack((a1,a2))        #20 Method>>>>>>> it will Stack arrays vertically
var12

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [75]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
         [4, 4]])
var12 = np.hstack((a1,a2))        #21 Method>>>>>>> it will Stack arrays Horizentally
var12

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [90]:
a = np.arange(1,25).reshape(2,12)
var13 = np.hsplit(a,3)           #22 Method>>>>>>> This method splits into many features
var13


[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [100]:
rng = np.random.default_rng(1)  #23 Method>>>>>>>> This method will set the defualt value
var14 = rng.random(3)           #24 Method>>>>>>>> This method will generate 3 ramdom numbers
var14

array([0.51182162, 0.9504637 , 0.14415961])

In [104]:
VAR15 = rng.integers(7, size=(2, 4)) #25 Method >>>>>> Used to genrate integer Random numbers
VAR15

array([[0, 3, 6, 0],
       [2, 2, 6, 1]])

In [106]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
var16 = np.unique(a)            #25 Method will distinct the values
var16

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [109]:
arr = np.arange(6).reshape((2, 3))
var17 = arr.transpose()          #26 it will reverse the axises
var17

array([[0, 3],
       [1, 4],
       [2, 5]])